name: sitesurface_flutter_openai
description: This Flutter package allows you to easily integrate OpenAI's API services into your Flutter application.
version: 0.0.2
homepage: https://sitesurface.com
repository: https://github.com/Sitesurface/sitesurface_flutter_openai

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
